### ISSUE TITLE
Mod Support

### ISSUE THREAD

**Issue by Madxmike** [TierZeroProductions/StacksOnStacks#12]
Confirmed Support:
Avarita
Thermal Foundation
BluePower
Aura Cascade
Botania
Redstone Arsenal
Pneumaticraft
Gregtech 5
Mekanism
Enderio
Mariculture
Gregtech6 - Not much more I can do
Metallurgy
Magneticraft
Project Red
BigReactors
Railcraft
Immersive Engineering
Magneticraft
Witchery
Practicalities

Improving Minecraft
TwilightForest

Texture Issues:
Rotarycraft
Extra Utilities
Magical Crops

Placement issues:
Randomthings

**Comment by Dominance** [comment]
The only thing I have found is it not being compatible with http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2296334-wip-kitsus-forgecraft-blacksmith-style-forging How ever I do not think it will ever be due to how the mod operates and allows placement on its own. Might want to include a incompatible list as well.

**Comment by lilmoefow** [comment]
For Botania, the only ingot that has an issue being placed seems to be the Gaia Spirit one, and could you add Blood Arsenal to the list as well???

**Comment by Madxmike** [comment]
http://imgur.com/WTkHOdg Botania and Aura Cascade ingots :)

After some rewriting to the ingot finder and resource finder I can now implement ingots really easily. More support will come probably monday as I'm busy all weekend sorry :(

**Comment by lilmoefow** [comment]
Don't be sorry dude, mods looking great :D

**Comment by bear989** [comment]
Rotorycraft HLSA steel ingots are just black, you also should add Gregteck to your list, so far every ingot I have placed with it looks great, I'm using your mod on 2 of my YT series to show it off for ya.

**Comment by Madxmike** [comment]
Rotarycraft and Gregtech are the two im going to be focusing on next. It will probably be a bit before they are fully usuable though due to their complexity.

**Comment by bear989** [comment]
I'm using it with GT5u and was actually amazed that the ingot piles where named properly since tin and invar from COFH doesn't. Your doing great man keep up the good work.

**Comment by Madxmike** [comment]
http://imgur.com/KxRLZQi gregtech 5 works 100%

**Comment by sivina** [comment]
Metallurgy 4 may be not supported yet :p?
http://i.imgur.com/yVyaaiu.png
this pic show that pile of ingots does not render the right color refer to the walia shows

if i sneak + left click to remove this pile of stacks, it crash me with this errors :p
http://pastebin.com/4FA0XwRR

great mods!! just got a head up on this issues :p

**Comment by Madxmike** [comment]
Heh I actually just added that to the list when I read your comment. Also the crash you posted should be fixed in the latest commit

**Comment by sivina** [comment]
oh derp derp x2 for me :p
thanks for the updates!

**Comment by Madxmike** [comment]
added thanks

**Comment by Alchimous** [comment]
The only ingots I'm unable to place in my current modpack are bedrockium(not really an issue, who has that much?), all the ingots from Tinkers' defence, and Koboldite from Witchery. I don't think an ingot stack for standard unstable ingots should exist, considering it's impossible to remove from a crafting table.

**Comment by MechWarrior99** [comment]
Just a heads up. It is compatible with Magneticraft so you can add it to the list of compatible mods :)

**Comment by bear989** [comment]
GT5 olivine gems render white when placed, also can you make rubber bars darker

**Comment by bear989** [comment]
GT5u thorium and rubber ingots same color as iron

**Comment by stclaus4** [comment]
add more mods like:
tinkers construct and extra TiC.
Extra Utilities.
the armory mod + modules would be great as well

**Comment by Dudblockman** [comment]
Automagy redcrystal (all variants) is placed as a stack and is unable to be placed normally, with or without shift key being pressed. Additionally redcrystal grabs a random texture that seems to be multiple images from a single sprite sheet.

**Comment by forcemaster89** [comment]
Great mod, I'm totally loving it. I did notice however, that it seems to be breaking the Colored Redstone from Gany's Surface mod. It tries to stack it when you place it, making it essentially unusable.

**Comment by Madxmike** [comment]
No longer supporting 1.7.10. Most placement issues can be sorted out with the config, just gotta find the name the item is registered under. It should either be the oredict name or the unlocalizedName.

**Comment by AlexanderBulanov** [comment]
I use bonemeal to grow my crops but every time I right click a plant to make it grow, it gives it the bonemeal effect and a pile of bonemeal is placed next to a crop. This happens to me regardless of the crop type. I tried to add dye, dyeWhite, minecraft, bonemeal, to the list of dusts that are blacklisted but there is no effect. Is there some name for bonemeal I'm missing?

**Comment by Madxmike** [comment]
90% sure its the name some mod is registering it under in the oredictionary. Sorry I can be more helpful. If anything you can update the mod to a version where I have forcefully disabled bonemeal.
