### ISSUE TITLE
Crash when using wrench to sneak right click a remove item events

### ISSUE THREAD

**Issue by sivina** [TierZeroProductions/StacksOnStacks#22]
Greetings,

This crash happens when i installed the stacks mods and doing what title says in the overworld, minecraft got freeze and cannot repsond until i hard close the Minecraft program.

I guess it may related to the ingots placing action and messing up with the wrenching events in TE since it all using sneaking + right click?i don't have a clue

Here goes for the error logs found in the files
http://pastebin.com/zdGtnuzw

I think i may need to put off this mod until is a fix since from now on i cannot remove any item that involve into sneaking right clicking items with a wrench.

Hope it got a fix in sometimes,Thanks!

**Comment by Madxmike** [comment]
This should be fixed in the new version as I've rewrote the placement handler to be much better.

**Comment by sivina** [comment]
Thanks for the updates!
Problems solved :P
