### ISSUE TITLE
Disable pile creation if right-click on a tile entity.

### ISSUE THREAD

**Issue by TheOnlyRupert** [TierZeroProductions/StacksOnStacks#28]
Enhancement:
If the block that the ingot, dust, or gem is clicked on is a tile entity and it has a GUI, it would be nice if the player would have to shift+right click on the block in order to place the item on the ground. There are many times that I go to craft something and i'm short one ingot because it is on the ground next to the crafting table.

**Comment by Madxmike** [comment]
What version are you using. This shouldn't be happening since 1.0.5

**Comment by TheOnlyRupert** [comment]
I apologize, I should have stated that
I am on the current version at the time (2.0.1). I just did some more testing, It seems like it is only happening on the Crafting Table, furnaces and other mod tile entities are fine.

**Comment by Madxmike** [comment]
Ok I'll look into it tomorrow.
