### ISSUE TITLE
Cauldron server disconnect on pile creation

### ISSUE THREAD

**Issue by TheOnlyRupert** [TierZeroProductions/StacksOnStacks#29]
I don't know if you guys are supporting Cauldron for this mod because this problem only happens with the recommended version of KCauldron from Yive (version: 1492.152). Normal Forge server works just fine.

In the most recent version (2.0.1), whenever shift is used to place a pile into the world (ingot, dusts, or gems), the client gets disconnected with a packet error. This only happens with pile creation and it doesn't matter if 1 or 64 of an item is placed down, if shift is used the client gets booted. Picking up full stacks off the ground with shift is unaffected.

I am not sure if you need anything else in the logs. The the sever error is: http://pastebin.com/mUkpf1Gw

**Comment by tyler489** [comment]
Same issue but it doesnt effect ops
