### ISSUE TITLE
No texture (Black) when running mod on a server 

### ISSUE THREAD

**Issue by That-Canadian** [TierZeroProductions/StacksOnStacks#3]
When I add the mod to a server (version 0.9.1) the stacks created used a pure black ingot texture. In a single player world with the same mod version, textures appear as expected. Re-logging does not fix the issue.

Image of gold stack on the server::
![ingotserver](https://cloud.githubusercontent.com/assets/6474430/9700241/dae6e7e8-53c9-11e5-81f4-9356a74111e6.png)

Same jar on single player:
![ingotsp](https://cloud.githubusercontent.com/assets/6474430/9700256/37f09164-53ca-11e5-87b7-52c3362a570c.png)

**Comment by primetoxinz** [comment]
update to 0.9.2, *might* work

**Comment by That-Canadian** [comment]
Ok so that sort of fixed it. Now all gold ingots have a tree texture.

Server picture::
![ingotserver](https://cloud.githubusercontent.com/assets/6474430/9700431/b0f4aaea-53d0-11e5-9eb3-40714a0056fb.png)


Single player picture::
![ingotsp](https://cloud.githubusercontent.com/assets/6474430/9700432/b7ee28f8-53d0-11e5-9c69-1391075c90e6.png)

Also I got a random null pointer exception client crash but I cannot recreate it. I can shoot you the log file if you'd like.

**Comment by primetoxinz** [comment]
yeah, logs would be nice

**Comment by That-Canadian** [comment]
No problem, here are two crash reports generated by the client. I'll try to recreate the crash and get you more info.

https://www.dropbox.com/sh/lk03va74tkp2cxj/AAA8ujg0voomry-nqy7o5OESa?dl=0

**Comment by primetoxinz** [comment]
can I also get the forge-latest log to fix the texture issue?

**Comment by That-Canadian** [comment]
Yea, let me find those for you.

Here are the latest FML logs from my client:
https://www.dropbox.com/sh/2by7es0m7ocuas2/AAAT_Tk-6mgloEXEtLcFI5g9a?dl=0

Logs 2 and 3 relate to the crash reports attached previously.

**Comment by primetoxinz** [comment]
if you can reproduce the crash I might be able to fix it, but the texture issue I can't reproduce. It might be some other mod messing with textures somehow

**Comment by That-Canadian** [comment]
No problem, I'll do more testing on my end.

**Comment by primetoxinz** [comment]
I'm just gonna put a config for the gold alt texture

**Comment by That-Canadian** [comment]
That seems to fix the gold ingot issue. As long as "goldAltTexture" is set to false it's fine. If I switch it over to true I get a texture error. Strange

**Comment by primetoxinz** [comment]
yeah, I know what line causes it, but not why
