### ISSUE TITLE
Crash when right clicking ground with Chromatic Craft crystals 

### ISSUE THREAD

**Issue by RoloEdits** [TierZeroProductions/StacksOnStacks#34]
http://pastebin.com/mh708VgA

**Comment by XFactHD** [comment]
Can you reproduce this without ForgeRelocation and/or Fastcraft?

**Comment by RoloEdits** [comment]
Yes, http://pastebin.com/ffkGs8rb

**Comment by Madxmike** [comment]
Should be fixed with 4ca8b04, or at least not crashing.

**Comment by RoloEdits** [comment]
OK, Thanks
