### ISSUE TITLE
[Rendering Crash]: RotaryCraft + Stacks on Stacks

### ISSUE THREAD

**Issue by Lanse505** [TierZeroProductions/StacksOnStacks#38]
CrashLog: http://pastebin.com/e2HZCEXx

**Comment by XFactHD** [comment]
Can you reproduce this without ForgeRelocation?

**Comment by primetoxinz** [comment]
yeah, what makes you think this is rotarycraft?

**Comment by Lanse505** [comment]
1. ForgeRelocation is a Library within Project Red that allows for the moving of blocks with frame.

2. Cause it happens when I create an "Gem Pile" with any of the "Gems" from Rotarycraft.

**Comment by Madxmike** [comment]
Pretty sure this is caused by the same thing as #34 so im closing it as a duplicate.
