### ISSUE TITLE
deletion if inventory is full

### ISSUE THREAD

**Issue by bear989** [TierZeroProductions/StacksOnStacks#39]
I found this with dusts(GT5 sulfur), and items(charcoal) so far

**Comment by primetoxinz** [comment]
can't reproduce, the items should get spawned into the world

**Comment by bear989** [comment]
I'll see if I can record it doing so

**Comment by bear989** [comment]
I haven't had it happen again, but I have seen other mods talking about a vanilla bug very similar so I don't think it was your mod causing the issue. feel free to close the issue.
