### ISSUE TITLE
Remove Lag

### ISSUE THREAD

**Issue by sci4me** [TierZeroProductions/StacksOnStacks#41]
I see a few issues with the rendering code in this mod that cause it's performance to be unideal.

The biggest issue is the fact that a TileEntitySpecialRenderer is being used instead of an ISimpleBlockRenderingHandler.
The TESR is unnecessary; you don't need to re-render the entire pile each frame. Instead, the pile should be re-rendered using an ISBRH only when it is modified.

**Comment by Madxmike** [comment]
The problem we had with it being a ISBRH was the gem piles wouldn't render correctly so we had to change it to a TESR IIRC. We'll look into it more though.

**Comment by sci4me** [comment]
Well, that's because of switching to the item texture right? A trick to get around that is this:
in the ISBRH, call tessellator.draw() at the very beginning, do your rendering (including tessellator.draw()), and then at the very end of the ISBRH, call tessellator.startDrawingQuads(). This should allow you to switch the texture to the item texture map.

**Comment by Madxmike** [comment]
wow no wonder its laggy as hell every single ingot/gem is getting its own draw call. So if you have a full pile of 64 ingots its doing 64 draws instead of the 1 with a ISBRH.

**Comment by sci4me** [comment]
Well another small thing is the fact that the TESR is instantiating a render object (PileRenderDust, PileRenderIngot, or PileRenderGem) in each frame which causes a lot of allocation overhead and tons of extra GC pressure which isn't needed at all.

**Comment by Madxmike** [comment]
Ya definitely doesnt help. I'm just going to rip it all out and redo it

**Comment by sci4me** [comment]
But like I said, the real salvation from lag is ISBRH... if at all possible it should be used.

**Comment by Madxmike** [comment]
Im going to try it first and see how it goes.

**Comment by sci4me** [comment]
Alright well, thanks! I look forward to seeing improvement. Keep me posted.

**Comment by Madxmike** [comment]
Done. See cd2fc4c

**Comment by sci4me** [comment]
http://pastebin.com/jVMVPBRY

**Comment by Madxmike** [comment]
Its fixed, but im testing a few things before I commit it.

**Comment by sci4me** [comment]
I'll wait for a proper release, but thanks again!

**Comment by Madxmike** [comment]
No problem, should be sometime tonight or tomorrow.

**Comment by sci4me** [comment]
Awesome! Glad to see this!
