### ISSUE TITLE
Dupe and stone spawning bug

### ISSUE THREAD

**Issue by axlegear** [TierZeroProductions/StacksOnStacks#42]
When you place a full stack (64) of any ingots, it spawns a stack of 64 plus 1 on top of a new stack.  If you shift-click the 64-stack it all disappears, but if you click the 1 on top it gives you the ingot and spawns a seemingly random number of stone blocks.  It seems the faster you click, the more stacks it produces.
Occurs in both 2.4.0 and 2.4.1.  Confirmed with multiple players on my server.  Had to revert to 2.2.0 which works fine.

**Comment by Madxmike** [comment]
This only occurs when placing down a full stack correct?

**Comment by Madxmike** [comment]
I'm pretty sure I know what's wrong and how to fix it but I won't have access to my computer until Tuesday

**Comment by Madxmike** [comment]
@primetoxinz if you want to fix this while I'm gone then add back the stack.stacksize > 0 to https://github.com/TierZeroProductions/StacksOnStacks/blob/master/src/main/java/com/tierzero/stacksonstacks/block/tile/TilePile.java#L51

It makes sure the comparator fix done inTierZeroProductions/StacksOnStacks/blob/master/src/main/java/com/tierzero/stacksonstacks/PileHandler.java#L76-L79 doesn't actually effect the state of the pile which is what us happening now.

95% sure that is the problem.
