### ISSUE TITLE
Add a different size of ingot.

### ISSUE THREAD

**Issue by sircrimer** [TierZeroProductions/StacksOnStacks#43]
Hi,
maybe you could add a different size of ingot? Something more along the lines of a big gold bar (basically making the ingot a bit narrower). It would add a bit of space between individual ingots in a stack and might look a bit less clustered.

Greetings
sircrimer

**Comment by Madxmike** [comment]
If I get the time ill look into it, but I wouldn't expect it anytime soon sorry.
