### ISSUE TITLE
Extending a stack past first block (64) UX

### ISSUE THREAD

**Issue by xarses** [TierZeroProductions/StacksOnStacks#46]
When taking off an items from a stack of stacks, shift right clicking pulls all the items from the highest stack (partial or full), however when placing we don't get the same experience.

In order to extend the stack, we have to be able to
1. see the top of the  (top) stack
2. click 3 times on the top of the stack, within the proper bounding area.

Expected UX would be to just shift click with more ingots on the bottom of the pile and they would magically end up on the top of the piles (reverse of removing them)

As a bonus, it would be quite awesome if we could do something like JABBA Barrels where we can [shift + double right click] and all of the matching item in the inventory where added to the stack (up to max stack height or an obscuring block)

**Comment by Madxmike** [comment]
What you described is how its intended to work. Sounds like a bug I got to look into.

**Comment by Madxmike** [comment]
I cant reproduce this at all. I am able to stack them how you describe, and how its intended to work, just fine.

**Comment by xarses** [comment]
Is it possible I have a CFG issue from a prior version?

**Comment by Madxmike** [comment]
The placement handler doesnt have anything in the config
