### ISSUE TITLE
Crash on placing Avaritia items.

### ISSUE THREAD

**Issue by YurgenJurgensen** [TierZeroProductions/StacksOnStacks#50]
Placing any ingots from Avaritia results in a world-destroying crash.  Looks like it can't get a texture for them.  I tried to blacklist the entire mod, but the configs didn't seem to do anything.

pastebin.com/nUKEft68

**Comment by Madxmike** [comment]
Should be fixed in 9109ca5aaa6c66a59622d09f72397bd5c9a7fa69
