### ISSUE TITLE
Color problem

### ISSUE THREAD

**Issue by Milobe115** [TierZeroProductions/StacksOnStacks#59]
I have quite a little problem with stacks colors. Here is a little example : http://i.imgur.com/z8a8AQH.png

The three ingots stacks are, from left to right : TiC Alumite, TiC Manyullun and TiC Bronze.

I use the Faithful modded resource pack, I don't have Optifine and I use the 2.4.3 version of Stacks On Stacks.

**Comment by Madxmike** [comment]
There isn't much I can do about this without screwing up colors for other mods sorry.
