### ISSUE TITLE
Heres a crash :)

### ISSUE THREAD

**Issue by Dominance** [TierZeroProductions/StacksOnStacks#6]
http://pastebin.com/ACbz4MK4 Happens on load. Didnt really look into it myself. Figured id pass on the info.

**Comment by primetoxinz** [comment]
it's because you have dragonapi without rotarycraft, my bad. for now disable the dragonapi compat in the config

**Comment by Dominance** [comment]
Ok thanks bud!

**Comment by primetoxinz** [comment]
will be fixed in release
