### ISSUE TITLE
Additional Ingot Support

### ISSUE THREAD

**Issue by lilmoefow** [TierZeroProductions/StacksOnStacks#8]
Would it be possible to get ingot support for blue power??  You can place ingots but the texture is black for every ingot type.  And Aura cascade aswell please if you can :-)

**Comment by Madxmike** [comment]
This will be a while sorry. The current way the stack is getting the texture is a mess and needs to be ripped out and redone to be able to support a lot more stuff.

**Comment by lilmoefow** [comment]
should this actually be closed??? maybe keep it open for the reminder or Aura Cascade ingots :P

**Comment by Madxmike** [comment]
I actually just got Aura Cascade ingots so the close is now 100% justified \o/

**Comment by lilmoefow** [comment]
Sweet :D
